['number_2 = fi(number_0,number_1)', 'answer_3 = fi(answer_1,answer_2)']
pragma solidity ^0.6.2;
['number_2 = fi(number_0,number_1)', 'answer_3 = fi(answer_1,answer_2)']
contract Sample{
    	int result_0;
		// address addr;
		// // int answer;
		// mapping (address => int) m;
	function factorial(int number_0) payable public returns(int){  
		// result = number + 10;    
		int answer_0;
		for(answer_1 = 1; number_0>1;number_1--){
      		answer_2 = answer_1 * number_0;
			// m[addr] = answer;
        	}
        result_2 = answer_3;
		// require(msg.value>0); this is not handled in CFG
		return result_2;
	}

	function factorial1(int number) public returns(int){      
		int answer;
		for(answer = 1; number>1;number--){
      		answer = answer * number;
        	}
        result = answer;
        return result;
		// answer = answer * number;
	}

}

// Here the below contract is used for checking the ast generated by solcx compiler
// contract Demo{
// 	int dummy;
// 	function customise_address(int x) public returns(int){
// 		dummy = x+20;
// 	}
// }